### ISSUE TITLE
requiring files from arbitrary folder without package.json

### ISSUE THREAD

**Issue by caridy** [zenparsing/es6-node-modules#5]
I suspect that this use-case is supposed to be solved by `require.import()` on the caller? Can you confirm?

**Comment by zenparsing** [comment]
If the target of the module specifier is a file, then the referencing module has to know what kind of module it is.

```js
// Referencing module is ES6
var oldModule = require('./folder/old-module.js');
import * as newModule from './folder/new-module.js');
```

```js
// Referencing module is CJS
var oldModule = require('./folder/old-module.js');
var newModule = require.import('./folder/new-module.js');
```

**Comment by caridy** [comment]
fair enough. there is a typo in the `import * ...` statement btw.
